# Generated by Django 5.0.2 on 2024-03-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='personal_id',
            field=models.CharField(max_length=10, verbose_name='Идентификатор'),
        ),
    ]
