# Generated by Django 5.0.2 on 2024-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_queue', '0003_patient_is_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.CharField(max_length=10, unique=True, verbose_name='Идентификатор')),
                ('surname', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('is_gold', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Remote_From_Queue_PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.CharField(max_length=10, unique=True, verbose_name='Идентификатор')),
                ('surname', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('is_gold', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Удаленный из очереди пациент',
                'verbose_name_plural': 'Удаленные из очереди пациенты',
            },
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
