# Generated by Django 5.0.2 on 2024-03-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_queue', '0004_patient_model_remote_from_queue_patientmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient_Model',
            new_name='PatientModel',
        ),
        migrations.RenameModel(
            old_name='Remote_From_Queue_PatientModel',
            new_name='RemoteFromQueuePatientModel',
        ),
    ]
