version: '3'

volumes:
  django: 

services:

  django:
    container_name: django_s
    build: 
      context: ../

      dockerfile: soup_system_settings/dockerfile
    volumes:
      - django:/usr/src/soup_system_settings
    ports:
      - "8000:8000"
   #depends_on:
   #  
   #  - mongodb
   #  - redis
    networks:
      - dbnetwork
  

  redis:
    image: redis:latest
    container_name: redis-container
    
    ports:
      - "6379:6379"
    networks:
      - dbnetwork

  mongodb:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    networks:
      - dbnetwork

  mongo-express:
    image: mongo-express
    container_name: mongo-web 
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=sudo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
    networks:
      - dbnetwork

networks:
  dbnetwork:
    driver: bridge
